[mypy]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-openai.*]
ignore_missing_imports = True

[mypy-anthropic.*]
ignore_missing_imports = True

[mypy-msal.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True
